name: macOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use a recent Xcode; 'latest-stable' tracks the newest GA version on the runner.
      # If you prefer pinning, use '17.x'.
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Show toolchain versions
        run: |
          xcodebuild -version
          xcrun swift --version

      - name: List schemes (project)
        run: xcodebuild -list -project "ColorPairStudio.xcodeproj"

      - name: Build & Test (unit tests only)
        run: |
          set -o pipefail
          xcodebuild \
            -project "ColorPairStudio.xcodeproj" \
            -scheme "ColorPairStudio" \
            -destination "platform=macOS" \
            -configuration Debug \
            -skip-testing "ColorPairStudioTestsUITests" \
            CODE_SIGNING_ALLOWED=NO \
            clean test
