name: macOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Show toolchain versions
        run: |
          xcodebuild -version
          xcrun swift --version

      - name: List schemes (project)
        run: xcodebuild -list -project "ColorPairStudio.xcodeproj"

      - name: Build (no tests for now)
        run: |
          set -o pipefail
          xcodebuild \
            -project "ColorPairStudio.xcodeproj" \
            -scheme "ColorPairStudio" \
            -destination "platform=macOS" \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            clean build
