name: macOS-CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  core-tests:
    name: ColorPairCore — package tests
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use an Xcode with Swift 6.0.x (compatible with // swift-tools-version: 6.0)
      - name: Set up Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Toolchain info
        run: |
          xcodebuild -version
          swift --version

      - name: Cache SPM (package)
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            ColorPairCore/.build
          key: ${{ runner.os }}-spm-${{ hashFiles('ColorPairCore/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Resolve dependencies
        working-directory: ColorPairCore
        run: swift package resolve

      - name: Run tests (parallel)
        working-directory: ColorPairCore
        run: swift test --parallel

  app-build:
    name: ColorPairStudio — build (no signing)
    runs-on: macos-15
    needs: core-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Toolchain info
        run: |
          xcodebuild -version
          swift --version

      - name: Cache DerivedData
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-derived-${{ hashFiles('**/*.xcodeproj/project.pbxproj') }}
          restore-keys: |
            ${{ runner.os }}-derived-

      - name: Build app (skip signing & UI tests)
        run: |
          set -o pipefail
          xcodebuild \
            -project "ColorPairStudio.xcodeproj" \
            -scheme "ColorPairStudio" \
            -destination "platform=macOS" \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES \
            clean build | tee xcodebuild.log

      - name: Upload build log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild.log
          path: xcodebuild.log
