name: macOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'   # or '16.x' to pin

      - name: Build & Test (unit tests)
        run: |
          set -o pipefail
          xcodebuild \
            -project "ColorPairStudio.xcodeproj" \
            -scheme "ColorPairStudio" \
            -destination "platform=macOS" \
            -configuration Debug \
            -only-testing "ColorPairStudioTests" \
            clean test
